name: CI - BDD Cucumber TestNG

on:
  push:
    branches: [ "Aravind_Cucumber" ]
  pull_request:
    branches: [ "Aravind_Cucumber" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean test

    - name: Upload Cucumber HTML Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-report
        path: target/cucumber-reports/