name: CI - BDD Cucumber TestNG

on:
  push:
    branches: [ "Aravind_Cucumber" ]
  pull_request:
    branches: [ "Aravind_Cucumber" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEADLESS: true   # This signals headless mode for both Selenium & Playwright

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Step 3: Build & run tests in headless mode
      - name: Build & run tests
        run: xvfb-run mvn -f MyProject/pom.xml clean test -Dheadless=true

      # Step 4: Upload test reports
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      # Step 5: Upload Cucumber HTML Report
      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/
