name: CI - BDD Cucumber TestNG

on:
  push:
    branches: [ "Aravind_Cucumber" ]
  pull_request:
    branches: [ "Aravind_Cucumber" ]
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Step 3: Build & run tests
      - name: Build with Maven
        run: mvn -f MyProject/pom.xml clean test -Dheadless=true

      # Step 4: Upload test reports as artifacts (use v4)
      - name: Upload test reports
        if: always() # ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      # Step 5: Upload Cucumber HTML report (if available)
      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/